'use strict';

module.exports = {
	webappDir : 'src/',
	buildDir:'build/',
	bower : 'src/main/webapp/bower_components/',
	port : 9000,
	uri : 'http://localhost:',
	constantTemplate : '(function () {\n' + '    \'use strict\';\n'
			+ '    // DO NOT EDIT THIS FILE\n' + '    angular\n'
			+ '        .module(\'<%- moduleName %>\')\n'
			+ '<% constants.forEach(function(constant) { %>        .constant(\'<%- constant.name %>\', <%= constant.value %>)\n<% }) %>;\n'
			+ '})();\n'
};
